"""Initial migration with indexes and constraints

Revision ID: 4b4a89d8378f
Revises: 
Create Date: 2026-03-24 16:23:30.747456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4a89d8378f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_check_history_api_key_id'), 'check_history', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_check_history_user_id'), 'check_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_history_user_id'), table_name='check_history')
    op.drop_index(op.f('ix_check_history_api_key_id'), table_name='check_history')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    # ### end Alembic commands ###
